"use client";
import { useRef, useState, type ReactNode, type PointerEvent } from "react";
import Link from "./OfflineLink";
import Icon from "./Icon";
import { SCHOOL_BOOKS, SCHOOL_CLASSES } from "@/lib/learning-resources";

const words = [{ hindi: "सूरज", english: "Sun", symbol: "☀", color: "sun" }, { hindi: "पेड़", english: "Tree", symbol: "♧", color: "tree" }, { hindi: "पानी", english: "Water", symbol: "◉", color: "water" }];
const stages = [
  { title: "Start with an idea.", text: "Turn a familiar topic into a lesson. Choose your class, add your teaching goals, and make it your own.", label: "Create a lesson", href: "/create-lesson", example: "Counting in our village", detail: "Mathematics · Class 1", items: ["Count the mangoes", "Find numbers around you", "Try a little quiz"] },
  { title: "Make language a bridge.", text: "Build Hindi–Santhali learning kits with vocabulary and explanations. Review translations before sharing them with your classroom.", label: "Explore lesson kits", href: "/lessons", example: "Words that feel like home", detail: "Hindi → Santhali", items: ["Learn in a familiar language", "Review vocabulary together", "Add your local context"] },
  { title: "Let curiosity lead.", text: "Bring books, activities and saved lessons together in a simple space made for your learners.", label: "Enter student mode", href: "/student/catalog", example: "Today’s little discoveries", detail: "Read · Explore · Practise", items: ["Open a learning kit", "Listen to saved lesson audio", "Celebrate a new discovery"] },
];
function DeskWindow({ title, className, children }: { title: string; className: string; children: ReactNode }) {
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const drag = useRef<{ x: number; y: number; startX: number; startY: number } | null>(null);
  const move = (e: PointerEvent<HTMLButtonElement>) => {
    if (!drag.current) return;
    setPosition({ x: Math.max(-45, Math.min(45, drag.current.startX + e.clientX - drag.current.x)), y: Math.max(-35, Math.min(35, drag.current.startY + e.clientY - drag.current.y)) });
  };
  return <div className={`desk-window ${className}`} style={{ translate: `${position.x}px ${position.y}px` }}>
    <button className="window-handle" aria-label={`Move ${title} card. Drag or use arrow keys; Home to reset.`} onPointerDown={e => { drag.current = { x: e.clientX, y: e.clientY, startX: position.x, startY: position.y }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={move} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }} onKeyDown={e => { if (["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Home"].includes(e.key)) { e.preventDefault(); setPosition(p => e.key === "Home" ? { x: 0, y: 0 } : { x: Math.max(-45, Math.min(45, p.x + (e.key === "ArrowRight" ? 10 : e.key === "ArrowLeft" ? -10 : 0))), y: Math.max(-35, Math.min(35, p.y + (e.key === "ArrowDown" ? 10 : e.key === "ArrowUp" ? -10 : 0))) }); } }}><span className="window-dots" aria-hidden="true">● ● ●</span>{title}<span aria-hidden="true">⠿</span></button>
    {children}
  </div>;
}
export default function LearningHome() {
  const [word, setWord] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [grade, setGrade] = useState(1);
  const [stage, setStage] = useState(0);
  const [deskKey, setDeskKey] = useState(0);
  const current = words[word];
  const featuredBook = SCHOOL_BOOKS.find(book => book.grade === grade && book.subject === "English")!;
  return <main className="new-home">
    <section className="discovery-hero">
      <div className="discovery-copy"><span className="mini-label"><span className="status-dot"/> ROOTED IN LANGUAGE. OPEN TO EVERYONE.</span><h1>Big dreams.<br/>Little steps.<br/><span>Our languages.</span><svg viewBox="0 0 420 20" aria-hidden="true"><path d="M5 13Q200-6 415 9M45 18Q220 4 365 15"/></svg></h1><p>A world of learning, closer to home. Discover books, create lessons, and let every child learn in a language they know.</p><div className="discovery-actions"><Link href="/learning" className="primary-action">Let’s explore <Icon name="arrow" size={19}/></Link><Link href="/teacher" className="text-action">I’m a teacher <span>↗</span></Link></div><div className="hero-footnote"><span className="tiny-orbit">अ</span><span>For curious minds in Classes 1–5<br/><b>Made for the joy of discovery.</b></span></div></div>
      <div className="learning-desk"><div className="desk-caption"><span>YOUR LITTLE LEARNING DESK</span><button onClick={() => setDeskKey(k => k + 1)}>Reset desk ↺</button></div><div className="desk-grid" key={deskKey}><span className="desk-spark spark-one" aria-hidden="true">✳</span><span className="desk-spark spark-two" aria-hidden="true">✦</span>
        <DeskWindow title="A word, a new world" className="word-window"><div className="word-card"><div className="card-overline">HINDI ↔ ENGLISH <span>{String(word + 1).padStart(2,"0")} / 03</span></div><button className={`word-flip ${current.color}`} aria-label={`Flip word card: ${flipped ? current.english : current.hindi}`} onClick={() => setFlipped(v => !v)}><span className="word-symbol" aria-hidden="true">{current.symbol}</span><strong key={`${word}-${flipped}`} lang={flipped ? "en" : "hi"}>{flipped ? current.english : current.hindi}</strong><small>Tap to discover the {flipped ? "Hindi" : "English"} word ↻</small></button><div className="word-controls"><span>Small words. Big connections.</span><button aria-label="Next word" onClick={() => { setWord(w => (w + 1) % words.length); setFlipped(false); }}>→</button></div></div></DeskWindow>
        <DeskWindow title="Find your next chapter" className="grade-window"><div className="grade-widget"><span className="mini-label">PICK YOUR CLASS</span><div className="desk-grades">{SCHOOL_CLASSES.map(n => <button key={n} aria-label={`Preview Class ${n}`} aria-pressed={grade === n} onClick={() => setGrade(n)}>{n}</button>)}</div><p aria-live="polite">Class {grade} · {featuredBook.title}</p><Link href={`/learning/books/${featuredBook.id}`}>Open this NCERT book <span>↗</span></Link></div></DeskWindow>
        <div className="desk-note"><span aria-hidden="true">✎</span><p>Every question<br/>is a beginning.</p><small>Stay curious.</small></div>
      </div><div className="desk-bottom"><span>↖ Drag the cards. Flip a word. Have a little fun.</span><span aria-hidden="true">✧</span></div></div>
    </section>
    <section className="discovery-strip home-stats" aria-label="Learning resources"><div><strong>{SCHOOL_CLASSES.length}</strong><span><b>Grade Levels</b><small>A little bigger, every year</small></span></div><div><strong>2</strong><span><b>Learning languages</b><small>Hindi & Santhali lesson kits</small></span></div><div><Icon name="book" size={32}/><span><b>NCERT, within reach</b><small>Read. Download. Rediscover.</small></span></div><div><Icon name="bookmark" size={30}/><span><b>Take learning along</b><small>Save resources for offline use</small></span></div></section>
    <section className="discovery-workflow" id="how-it-works"><div className="editorial-heading"><span className="mini-label">FROM A SPARK TO A LESSON</span><h2>Good learning starts<br/>with a little curiosity<span>.</span></h2><p>Thoughtful tools for teachers.<br/>A whole world of possibilities for children.</p></div><div className="journey-tabs" role="tablist" aria-label="Learning journey">{["Create something", "Connect languages", "Learn together"].map((name,i) => <button key={name} id={`journey-tab-${i}`} role="tab" aria-selected={stage === i} aria-controls="journey-panel" tabIndex={stage === i ? 0 : -1} onKeyDown={e => { if (e.key === "ArrowRight" || e.key === "ArrowLeft") { e.preventDefault(); const next = (stage + (e.key === "ArrowRight" ? 1 : 2)) % 3; setStage(next); document.getElementById(`journey-tab-${next}`)?.focus(); } }} onClick={() => setStage(i)}><span>0{i + 1}</span>{name}<span>↗</span></button>)}</div><div className="journey-panel" id="journey-panel" role="tabpanel" aria-labelledby={`journey-tab-${stage}`}><div><h3>{stages[stage].title}</h3><p>{stages[stage].text}</p><Link href={stages[stage].href} className="text-action">{stages[stage].label} <span>→</span></Link></div><div className="lesson-preview" key={stage}><div className="preview-top"><span>✳ LESSON NOTEBOOK</span><Icon name="book" size={20}/></div><small>{stages[stage].detail}</small><h4>{stages[stage].example}</h4>{stages[stage].items.map((item,i) => <div className="preview-item" key={item}><span>{i + 1}</span>{item}<Icon name="check" size={15}/></div>)}</div></div></section>
    <section className="explore-bento"><Link href="/learning" className="bento-books"><span className="mini-label">THE LEARNING HUB <span>↗</span></span><h2>A bookshelf full<br/>of possibilities.</h2><p>NCERT books for Classes 1–5.<br/>One lovely place to begin.</p><div className="book-spines" aria-hidden="true"><span>DISCOVER</span><span>READ</span><span>IMAGINE</span><span>GROW</span></div></Link><Link href="/learning/dictionary" className="bento-dictionary"><span className="mini-label">LITTLE DICTIONARY <span>↗</span></span><div className="letter-pair" aria-hidden="true">अ<span>↔</span>A</div><h2>New words.<br/>New worlds.</h2><p>Explore Hindi and English, one word at a time.</p></Link><Link href="/offline" className="bento-offline"><span className="mini-label">READY WHEN YOU ARE <span>↗</span></span><Icon name="bookmark" size={38}/><h2>Learning<br/>to go.</h2><p>Download books and save lessons before you go offline.</p><span className="bento-link">Set up offline access →</span></Link></section>
    <section className="home-questions"><div><span className="mini-label">A FEW THINGS TO KNOW</span><h2>Small questions.<br/>Clear answers.</h2></div><div>{[{ q: "Where should I start?", a: "Open the Learning Hub to browse NCERT books for Classes 1–5, or visit the Teacher Dashboard to create and review lesson kits." }, { q: "Can I use it without the internet?", a: "Yes, downloaded books, saved lessons and cached audio work offline after setup. Visit Offline Access while connected to prepare your device. New AI lessons require a supported installed model; new speech depends on your device and language." }, { q: "Which languages can I explore?", a: "Lesson tools support Hindi–Santhali learning kits. The little dictionary helps learners explore Hindi and English. Teachers should review generated translations before classroom use." }].map(item => <details key={item.q}><summary>{item.q}<span aria-hidden="true">+</span></summary><p>{item.a}</p></details>)}</div></section>
    <section className="discovery-end"><span className="mini-label">EVERY CHILD. EVERY LANGUAGE.</span><h2>A little curiosity.<br/>An endless beginning<span>✳</span></h2><Link href="/learning" className="primary-action">Find your next discovery <Icon name="arrow" size={20}/></Link></section>
  </main>;
}
