import { LearningKit, SavedLesson } from "@/types/lesson";

/**
 * Canonical demo lesson data for VaaniShiksha.
 *
 * IMPORTANT: This Santhali content was generated by Gemini AI and has NOT been
 * independently verified by a native Santhali linguist. The verificationStatus
 * is set to "ai_generated" to reflect this honestly.
 *
 * Single source of truth — imported by storage.ts and student/page.tsx.
 */

export const DEMO_LEARNING_KIT: LearningKit = {
  title: "Plants Around Us (हमारे आसपास के पौधे / ᱟᱵᱚ ᱨᱮᱱᱟᱜ ᱫᱟᱨᱮ ᱠᱚ)",
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  grade: "Grade 2",
  subject: "Environmental Studies",
  verificationStatus: "ai_generated",
  lesson: {
    hindi:
      "हमारे आसपास कई प्रकार के पौधे होते हैं। कुछ पौधे बड़े होते हैं जिन्हें पेड़ कहते हैं, और कुछ पौधे छोटे होते हैं।",
    santhali:
      "ᱟᱵᱚ ᱯᱟᱦᱴᱟ ᱨᱮ ᱟᱭᱢᱟ ᱞᱮᱠᱟᱱ ᱫᱟᱨᱮ ᱠᱚ ᱢᱮᱱᱟᱜ-ᱟ: ᱫᱟᱨᱮ (Dare), ᱥᱟᱠᱟᱢ (Sakam), ᱵᱟᱦᱟ (Baha) ᱟᱨ ᱨᱮᱦᱮᱫ (Rehed)᱾",
    romanization:
      "Abo pahta re aima lekan dare ko menag-a: dare, sakam, baha ar rehed.",
    simpleExplanation:
      "पौधों के अलग-अलग भाग जैसे जड़, तना, पत्ता और फूल हमारे जीवन के लिए अति आवश्यक हैं।",
  },
  vocabulary: [
    {
      hindi: "पौधा (Paudha)",
      santhali: "ᱫᱟᱨᱮ",
      romanization: "Dare",
      meaning:
        "A living thing that grows in earth with roots, stems, and leaves.",
    },
    {
      hindi: "पत्ता (Patta)",
      santhali: "ᱥᱟᱠᱟᱢ",
      romanization: "Sakam",
      meaning: "The flat green part of a plant that catches sunlight.",
    },
    {
      hindi: "फूल (Phool)",
      santhali: "ᱵᱟᱦᱟ",
      romanization: "Baha",
      meaning: "The colorful part of a plant that blooms.",
    },
    {
      hindi: "जड़ (Jad)",
      santhali: "ᱨᱮᱦᱮᱫ",
      romanization: "Rehed",
      meaning: "The part underground that drinks water for the plant.",
    },
  ],
  flashcards: [
    {
      front: "पौधे को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱫᱟᱨᱮ (Dare) - Plant / Tree",
    },
    {
      front: "पत्ते को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱥᱟᱠᱟᱢ (Sakam) - Leaf",
    },
    {
      front: "फूल को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱵᱟᱦᱟ (Baha) - Flower",
    },
    {
      front: "जड़ को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱨᱮᱦᱮᱫ (Rehed) - Root",
    },
  ],
  quiz: [
    {
      question: "पौधे का कौन सा भाग ज़मीन के नीचे रहता है?",
      options: [
        "ᱥᱟᱠᱟᱢ (Sakam / पत्ता)",
        "ᱨᱮᱦᱮᱫ (Rehed / जड़)",
        "ᱵᱟᱦᱟ (Baha / फूल)",
        "ᱫᱟᱨᱮ (Dare / पौधा)",
      ],
      correctAnswer: "ᱨᱮᱦᱮᱫ (Rehed / जड़)",
    },
    {
      question: "संथाली शब्द 'ᱵᱟᱦᱟ' (Baha) का हिंदी अर्थ क्या है?",
      options: ["जड़", "तना", "फूल", "फल"],
      correctAnswer: "फूल",
    },
  ],
  activity: {
    title: "Leaf Collector Challenge (ᱥᱟᱠᱟᱢ Game)",
    instructions:
      "1. Find 3 different leaves in your school yard.\n2. Bring them to class and say their names in Santhali (ᱥᱟᱠᱟᱢ - Sakam) to your teacher!",
  },
  quality: {
    // P1-3: Metadata consistent with "not independently verified" disclaimer
    reviewRequired: true,
    confidence: "medium",
    reviewNotes:
      "AI-generated demo lesson. Standard Santhali primary botanical terms in Ol Chiki script. Not independently verified by a native Santhali linguist.",
  },
};

export const DEMO_SAVED_LESSON: SavedLesson = {
  id: "demo-plants-around-us",
  title: DEMO_LEARNING_KIT.title,
  grade: DEMO_LEARNING_KIT.grade,
  subject: DEMO_LEARNING_KIT.subject,
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  verificationStatus: "ai_generated",
  kit: DEMO_LEARNING_KIT,
};
