import { LearningKit, SavedLesson } from "@/types/lesson";

/**
 * Canonical demo lesson data for VaaniShiksha.
 *
 * IMPORTANT: This Santhali content was generated by Gemini AI and has NOT been
 * independently verified by a native Santhali linguist. The verificationStatus
 * is set to "ai_generated" to reflect this honestly.
 *
 * Single source of truth — imported by storage.ts and student/page.tsx.
 */

export const DEMO_LEARNING_KIT: LearningKit = {
  title: "Plants Around Us (हमारे आसपास के पौधे / ᱟᱵᱚ ᱨᱮᱱᱟᱜ ᱫᱟᱨᱮ ᱠᱚ)",
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  grade: "Grade 2",
  subject: "Environmental Studies",
  verificationStatus: "ai_generated",
  lesson: {
    hindi:
      "हमारे आसपास कई प्रकार के पौधे होते हैं। कुछ पौधे बड़े होते हैं जिन्हें पेड़ कहते हैं, और कुछ पौधे छोटे होते हैं।",
    santhali:
      "ᱟᱵᱚ ᱯᱟᱦᱴᱟ ᱨᱮ ᱟᱭᱢᱟ ᱞᱮᱠᱟᱱ ᱫᱟᱨᱮ ᱠᱚ ᱢᱮᱱᱟᱜ-ᱟ: ᱫᱟᱨᱮ (Dare), ᱥᱟᱠᱟᱢ (Sakam), ᱵᱟᱦᱟ (Baha) ᱟᱨ ᱨᱮᱦᱮᱫ (Rehed)᱾",
    romanization:
      "Abo pahta re aima lekan dare ko menag-a: dare, sakam, baha ar rehed.",
    simpleExplanation:
      "पौधों के अलग-अलग भाग जैसे जड़, तना, पत्ता और फूल हमारे जीवन के लिए अति आवश्यक हैं।",
  },
  vocabulary: [
    {
      hindi: "पौधा (Paudha)",
      santhali: "ᱫᱟᱨᱮ",
      romanization: "Dare",
      meaning:
        "A living thing that grows in earth with roots, stems, and leaves.",
    },
    {
      hindi: "पत्ता (Patta)",
      santhali: "ᱥᱟᱠᱟᱢ",
      romanization: "Sakam",
      meaning: "The flat green part of a plant that catches sunlight.",
    },
    {
      hindi: "फूल (Phool)",
      santhali: "ᱵᱟᱦᱟ",
      romanization: "Baha",
      meaning: "The colorful part of a plant that blooms.",
    },
    {
      hindi: "जड़ (Jad)",
      santhali: "ᱨᱮᱦᱮᱫ",
      romanization: "Rehed",
      meaning: "The part underground that drinks water for the plant.",
    },
  ],
  flashcards: [
    {
      front: "पौधे को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱫᱟᱨᱮ (Dare) - Plant / Tree",
    },
    {
      front: "पत्ते को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱥᱟᱠᱟᱢ (Sakam) - Leaf",
    },
    {
      front: "फूल को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱵᱟᱦᱟ (Baha) - Flower",
    },
    {
      front: "जड़ को संथाली (Ol Chiki) में क्या कहते हैं?",
      back: "ᱨᱮᱦᱮᱫ (Rehed) - Root",
    },
  ],
  quiz: [
    {
      question: "पौधे का कौन सा भाग ज़मीन के नीचे रहता है?",
      options: [
        "ᱥᱟᱠᱟᱢ (Sakam / पत्ता)",
        "ᱨᱮᱦᱮᱫ (Rehed / जड़)",
        "ᱵᱟᱦᱟ (Baha / फूल)",
        "ᱫᱟᱨᱮ (Dare / पौधा)",
      ],
      correctAnswer: "ᱨᱮᱦᱮᱫ (Rehed / जड़)",
    },
    {
      question: "संथाली शब्द 'ᱵᱟᱦᱟ' (Baha) का हिंदी अर्थ क्या है?",
      options: ["जड़", "तना", "फूल", "फल"],
      correctAnswer: "फूल",
    },
  ],
  activity: {
    title: "Leaf Collector Challenge (ᱥᱟᱠᱟᱢ Game)",
    instructions:
      "1. Find 3 different leaves in your school yard.\n2. Bring them to class and say their names in Santhali (ᱥᱟᱠᱟᱢ - Sakam) to your teacher!",
  },
  quality: {
    // P1-3: Metadata consistent with "not independently verified" disclaimer
    reviewRequired: true,
    confidence: "medium",
    reviewNotes:
      "AI-generated demo lesson. Standard Santhali primary botanical terms in Ol Chiki script. Not independently verified by a native Santhali linguist.",
  },
};

export const DEMO_SAVED_LESSON: SavedLesson = {
  id: "demo-plants",
  title: DEMO_LEARNING_KIT.title,
  grade: DEMO_LEARNING_KIT.grade,
  subject: DEMO_LEARNING_KIT.subject,
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  verificationStatus: "ai_generated",
  kit: DEMO_LEARNING_KIT,
};

export const DEMO_SAVED_LESSON_COUNTING: SavedLesson = {
  id: "demo-counting",
  title: "Numbers 1–20 (संख्याएँ 1 से 20)",
  grade: "Grade 1",
  subject: "Mathematics",
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  verificationStatus: "ai_generated",
  kit: {
    title: "Numbers 1–20 (संख्याएँ 1 से 20)",
    sourceLanguage: "Hindi",
    targetLanguage: "Santhali",
    grade: "Grade 1",
    subject: "Mathematics",
    verificationStatus: "ai_generated",
    lesson: {
      hindi: "आज हम एक से बीस तक की संख्याएँ सीखेंगे।",
      santhali: "ᱛᱮᱦᱮᱧ ᱟᱵᱚ ᱢᱤᱫ ᱠᱷᱚᱱ ᱵᱟᱨᱜᱮᱞ ᱫᱷᱟᱹᱵᱤᱡ ᱮᱞᱠᱷᱟ ᱵᱚᱱ ᱪᱮᱫᱚᱜ-ᱟ᱾",
      romanization: "Teheñ abo mid khon bargel dhäbij elkha bon chedog-a.",
      simpleExplanation: "गिनती सीखना गणित का पहला कदम है।",
    },
    vocabulary: [
      {
        hindi: "एक (Ek)",
        santhali: "ᱢᱤᱫ",
        romanization: "Mid",
        meaning: "The number one.",
      },
      {
        hindi: "दो (Do)",
        santhali: "ᱵᱟᱨ",
        romanization: "Bar",
        meaning: "The number two.",
      },
      {
        hindi: "तीन (Teen)",
        santhali: "ᱯᱮ",
        romanization: "Pe",
        meaning: "The number three.",
      },
      {
        hindi: "चार (Char)",
        santhali: "ᱯᱩᱱ",
        romanization: "Pun",
        meaning: "The number four.",
      },
    ],
    flashcards: [
      {
        front: "एक को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱢᱤᱫ (Mid) - One",
      },
      {
        front: "दो को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱵᱟᱨ (Bar) - Two",
      },
      {
        front: "तीन को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱯᱮ (Pe) - Three",
      },
    ],
    quiz: [
      {
        question: "संथाली में 'दो' (Two) को क्या कहते हैं?",
        options: ["ᱢᱤᱫ (Mid)", "ᱵᱟᱨ (Bar)", "ᱯᱮ (Pe)", "ᱯᱩᱱ (Pun)"],
        correctAnswer: "ᱵᱟᱨ (Bar)",
      },
      {
        question: "'ᱢᱤᱫ' (Mid) का अर्थ क्या है?",
        options: ["एक (1)", "दो (2)", "तीन (3)", "चार (4)"],
        correctAnswer: "एक (1)",
      },
    ],
    activity: {
      title: "Counting Challenge",
      instructions: "1. Find 3 identical items in the classroom (e.g. pencils).\n2. Count them aloud in Santhali for your teacher!",
    },
    quality: {
      reviewRequired: true,
      confidence: "high",
      reviewNotes: "Standard numbers 1-4 in Santhali.",
    }
  },
};

export const DEMO_SAVED_LESSON_ANIMALS: SavedLesson = {
  id: "demo-animals",
  title: "Animals Around Us (हमारे आसपास के जानवर)",
  grade: "Grade 3",
  subject: "Science",
  sourceLanguage: "Hindi",
  targetLanguage: "Santhali",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  verificationStatus: "ai_generated",
  kit: {
    title: "Animals Around Us (हमारे आसपास के जानवर)",
    sourceLanguage: "Hindi",
    targetLanguage: "Santhali",
    grade: "Grade 3",
    subject: "Science",
    verificationStatus: "ai_generated",
    lesson: {
      hindi: "हमारे आसपास कई जानवर होते हैं, जैसे कुत्ता, बिल्ली, और गाय।",
      santhali: "ᱟᱵᱚ ᱯᱟᱦᱴᱟ ᱨᱮ ᱟᱭᱢᱟ ᱡᱟᱱᱣᱟᱨ ᱢᱮᱱᱟᱜ ᱠᱚᱣᱟ, ᱡᱮᱞᱮᱠᱟ ᱥᱮᱛᱟ, ᱯᱩᱥᱤ, ᱟᱨ ᱜᱟᱹᱭ᱾",
      romanization: "Abo pahta re aima janwar menag kowa, jeleka seta, pusi, ar gäy.",
      simpleExplanation: "जानवर हमारे पर्यावरण का महत्वपूर्ण हिस्सा हैं।",
    },
    vocabulary: [
      {
        hindi: "कुत्ता (Kutta)",
        santhali: "ᱥᱮᱛᱟ",
        romanization: "Seta",
        meaning: "A common pet animal, dog.",
      },
      {
        hindi: "बिल्ली (Billi)",
        santhali: "ᱯᱩᱥᱤ",
        romanization: "Pusi",
        meaning: "A small pet animal, cat.",
      },
      {
        hindi: "गाय (Gaay)",
        santhali: "ᱜᱟᱹᱭ",
        romanization: "Gay",
        meaning: "A farm animal that gives milk, cow.",
      },
      {
        hindi: "पक्षी (Pakshi)",
        santhali: "ᱪᱮᱬᱮ",
        romanization: "Cene",
        meaning: "Animals that can fly, bird.",
      },
    ],
    flashcards: [
      {
        front: "कुत्ते को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱥᱮᱛᱟ (Seta) - Dog",
      },
      {
        front: "बिल्ली को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱯᱩᱥᱤ (Pusi) - Cat",
      },
      {
        front: "गाय को संथाली (Ol Chiki) में क्या कहते हैं?",
        back: "ᱜᱟᱹᱭ (Gay) - Cow",
      },
    ],
    quiz: [
      {
        question: "कुत्ते को संथाली में क्या कहते हैं?",
        options: ["ᱯᱩᱥᱤ (Pusi)", "ᱥᱮᱛᱟ (Seta)", "ᱜᱟᱹᱭ (Gay)", "ᱪᱮᱬᱮ (Cene)"],
        correctAnswer: "ᱥᱮᱛᱟ (Seta)",
      },
      {
        question: "'ᱜᱟᱹᱭ' (Gay) का अर्थ क्या है?",
        options: ["बिल्ली", "कुत्ता", "गाय", "पक्षी"],
        correctAnswer: "गाय",
      },
    ],
    activity: {
      title: "Animal Sounds & Names",
      instructions: "1. Draw your favorite animal from today's lesson.\n2. Write its Santhali name under the drawing and make its sound!",
    },
    quality: {
      reviewRequired: true,
      confidence: "high",
      reviewNotes: "Common domestic animals in Santhali.",
    }
  },
};
